name: Create Archive
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'quickrn-template-basic.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          path: './template'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: 'quickrn-template-basic.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'v1.0'
